services:
    sonata.admin.user:
        class: App\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [UserBundle]]