services:
    sonata.admin.user:
        class: App\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "用户", label: "用户管理" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [UserBundle]]
    sonata.admin.group:
        class: App\UserBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "用户", label: "部门管理" }
        arguments:
            - ~
            - App\UserBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [UserBundle]]