services:
    sonata.admin.repair:
        class: App\RepairBundle\Admin\RepairFormAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Repair", label: "RepairForm" }
        arguments:
            - ~
            - App\RepairBundle\Entity\RepairForm
            - ~
        calls:
            - [ setTranslationDomain, [RepairBundle]]
    sonata.admin.faultInfo:
        class: App\RepairBundle\Admin\FaultInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Repair", label: "FaultInfo" }
        arguments:
            - ~
            - App\RepairBundle\Entity\FaultInfo
            - ~
        calls:
            - [ setTranslationDomain, [RepairBundle]]