services:
    sonata.admin.repair:
        class: App\RepairBundle\Admin\RepairFormAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "维修", label: "工单信息" }
        arguments:
            - ~
            - App\RepairBundle\Entity\RepairForm
            - ~
        calls:
            - [ setTranslationDomain, [RepairBundle]]
    sonata.admin.faultInfo:
        class: App\RepairBundle\Admin\FaultInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "维修", label: "故障信息" }
        arguments:
            - ~
            - App\RepairBundle\Entity\FaultInfo
            - ~
        calls:
            - [ setTranslationDomain, [RepairBundle]]