parameters:
    app.repair.pre_content_view.class: App\RepairBundle\EventListener\PreContentViewListener

services:
    app.repair.pre_content_view:
        class: %app.repair.pre_content_view.class%
        tags:
            -{ name: kernel.event_listener, event: kernel.view, method: onPreContentView }
#    app.repair.example:
#        class: %app.repair.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }